version: 2
jobs:
  php_test:
    docker:
      - image: 7.4.0rc3-alpine
        environment:
          CIRCLE_TEST_REPORTS: ~/report
    steps:
      - checkout
      - run:
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('sha384', 'composer-setup.php') === 'a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php --install-dir=/usr/local/bin --filename=composer
            php -r "unlink('composer-setup.php');"
      - run: sudo composer self-update
      - restore_cache:
          key: composer-v1-{{ checksum "money/composer.lock" }}
      - run: composer install --dev --no-interaction --working-dir=money/
      - save_cache:
          key: composer-v1-{{ checksum "money/composer.lock" }}
          paths:
            - "/home/ubuntu/.composer/cache"
      - run: money/vendor/bin/phpunit money/tests --log-junit $CIRCLE_TEST_REPORTS/phpunit/money-junit.xml

workflows:
  version: 2
  build-all:
    jobs:
      - php_test
